### ISSUE TITLE
Error when website is not on HTTPS

### ISSUE THREAD

**Issue by cyb3rd3s** [cyb3rd3s/WPvSCAN#3]
Script end up with error, if website doesn't have SSL certificate:

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>`

**Comment by rodriguezjorgex** [comment]
Can I submit a pull request? I would like to work on this bug to help me with my troubleshooting skills.

**Comment by cyb3rd3s** [comment]
@rodriguezjorgex sure! Feel free to help me and make OUR script better :)
